/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificatesAcademicRouteImport } from './routes/certificates.academic'
import { Route as CertificatesInterestsRouteImport } from './routes/certificates.interests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesAcademicRoute = CertificatesAcademicRouteImport.update({
  id: '/certificates/academic',
  path: '/certificates/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesInterestsRoute = CertificatesInterestsRouteImport.update({
  id: '/certificates/interests',
  path: '/certificates/interests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificates/academic': typeof CertificatesAcademicRoute
  '/certificates/interests': typeof CertificatesInterestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificates/academic': typeof CertificatesAcademicRoute
  '/certificates/interests': typeof CertificatesInterestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificates/academic': typeof CertificatesAcademicRoute
  '/certificates/interests': typeof CertificatesInterestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificates/academic' | '/certificates/interests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificates/academic' | '/certificates/interests'
  id: '__root__' | '/' | '/certificates/academic' | '/certificates/interests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificatesAcademicRoute: typeof CertificatesAcademicRoute
  CertificatesInterestsRoute: typeof CertificatesInterestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/academic': {
      id: '/certificates/academic'
      path: '/certificates/academic'
      fullPath: '/certificates/academic'
      preLoaderRoute: typeof CertificatesAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/interests': {
      id: '/certificates/interests'
      path: '/certificates/interests'
      fullPath: '/certificates/interests'
      preLoaderRoute: typeof CertificatesInterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificatesAcademicRoute: CertificatesAcademicRoute,
  CertificatesInterestsRoute: CertificatesInterestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
